### ISSUE TITLE
Create a docker container to run the app

### ISSUE THREAD

**Issue by jmMeessen** [on4kjm/FLEcli#15]
One of the alternatives as I am not able to provide a signed MacOS binary (issue #9 ).

**Comment by jmMeessen** [comment]
To push to Docker hub:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
```
see https://stackoverflow.com/questions/58226756/how-to-login-to-docker-registries-using-github-actions
and https://stackoverflow.com/questions/58350578/new-location-of-docker-actions/58350591#58350591
